"""initial schema

Revision ID: 03cf84a2a4e1
Revises: 
Create Date: 2026-09-14 05:21:36.917404

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '03cf84a2a4e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('branch', sa.String(length=1), nullable=True),
    sa.Column('is_fiction', sa.Boolean(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('current_stage_years', sa.Float(), nullable=True),
    sa.Column('tier1_capital', sa.Float(), nullable=True),
    sa.Column('tier2_capital', sa.Float(), nullable=True),
    sa.Column('vsaa_registration_date', sa.Date(), nullable=True),
    sa.Column('monthly_base', sa.Float(), nullable=True),
    sa.Column('first_payment_date', sa.Date(), nullable=True),
    sa.Column('stage_check_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_dec15_reminded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('lv_employment_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lv_employment_periods_user_id'), 'lv_employment_periods', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('marked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_payment_month')
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_lv_employment_periods_user_id'), table_name='lv_employment_periods')
    op.drop_table('lv_employment_periods')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
