"""add employer_name to lv_employment_periods

Revision ID: 1e88ed83a70d
Revises: 03cf84a2a4e1
Create Date: 2026-09-14 07:54:53.644763

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e88ed83a70d'
down_revision: Union[str, Sequence[str], None] = '03cf84a2a4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lv_employment_periods', sa.Column('employer_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lv_employment_periods', 'employer_name')
    # ### end Alembic commands ###
