"""add tier3_capital to users

Revision ID: 3577c64f168b
Revises: 1e88ed83a70d
Create Date: 2026-09-15 16:36:08.579340

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3577c64f168b'
down_revision: Union[str, Sequence[str], None] = '1e88ed83a70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier3_capital', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier3_capital')
    # ### end Alembic commands ###
